### PR TITLE
Fix spaces before parenthesis openings

### PR DESCRIPTION
**Pull request by shubham1172**
Signed-off-by: Shubham Sharma <shubhash@microsoft.com>

### CODE REVIEW

**Comment by shubham1172** [comment]
@a-muk did you get a chance to review this?

**Review by attreyee-muk — COMMENTED** [review]
I think it's fine right now. I was just a bit worried with the code samples, but it seems like the change hasn't occurred on those.

**Comment by attreyee-muk** [comment]
@shubham1172 Shall I merge it now?

**Comment by shubham1172** [comment]
Yes, I have fixed those. Please merge it if it looks good to you.

**Pull request merged**
